### PR TITLE
add delete support

### PR DESCRIPTION
**Pull request by sirexeclp**
using correction mode and reverse printing
this implements issue #34

### CODE REVIEW

**Comment by ArchibaldBienetre** [comment]
Please have a look at the requirements described in https://github.com/Chaostreff-Potsdam/erika3004/issues/34#issue-545393620

I'd really like there to be some simple test + support for CharacterBasedErikaMock.

Plus: Let's wait for the big upcoming merge of 
https://github.com/Chaostreff-Potsdam/erika3004/pull/28

**Comment by sirexeclp** [comment]
First Hardware test was successful.
method expects string in reversed order

**Comment by ArchibaldBienetre** [comment]
I'm a bit confused, will code tests according to the way I assume the hardware will work.

Generally, I would have assumed
* I type "Hello"
* I call delete_ascii("olle")
  * the device will move back 1 step, delete the o, and so on...
  * the device will end up with the cursor _next to_ the H, ready for typing?

? 

That is what I would assume from manual operation of the device. 

Seeing the code, though, I think it wil work like so: 
* I type "Hello"
* I need to reposition the device above the "o" (move left 1 normal step)
* I call delete_ascii("olle")
  * the device overprints the letters in order
  * the device will end up with the cursor _above_ the H

I will write tests assuming the latter, for now.

From a user's point of view, I'm unsure what they will expect - when in doubt, let's add a comment that clarifies this.

**Comment by ArchibaldBienetre** [comment]
"Manual" test script I used to verify delete_ascii works: 
I just took the unit test + watched that the curses output also works out. 

```
from erika.erika_mock import CharacterBasedErikaMock

with CharacterBasedErikaMock(width=5, height=1, inside_unit_test=True, exception_if_overprinted=False) as my_erika:
    my_erika.print_ascii("Hello")

    my_erika.move_left()
    my_erika.delete_ascii("o")

    my_erika.delete_ascii("lle")

    my_erika.move_right()
    my_erika.print_ascii("elp")
    my_erika.wait_for_user_if_simulated()
```

In retrospect, I guess I could have tested (and automated the test as part of the existing one) using 
[`inch(y, x)`](https://docs.python.org/3.5/library/curses.html#curses.window.inch)

**Pull request merged**
